# Generated by Django 5.1.2 on 2024-10-27 06:17

import inventory.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_category_options_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=inventory.fields.ProductDescriptionField(default='Test description', help_text='Describe your product'),
        ),
    ]
