# Generated by Django 5.1.2 on 2024-10-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='color',
            field=models.CharField(choices=[('RD', 'Red'), ('BL', 'Blue')], max_length=50),
        ),
    ]
